[package]
name = "door"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[workspace]
members = [
    "sshproto",
    "smol",
    "door-tokio",
]

[profile.release]
opt-level = 's'
# lto = "fat"
debug = 1

[patch."https://github.com/mkj/ring"]
ring = { path = "/home/matt/3rd/rs/ring" }

[patch."https://github.com/mkj/ed25519-dalek"]
ed25519-dalek = { path = "/home/matt/3rd/rs/ed25519-dalek" }
