[package]
name = "door"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[workspace]
members = [
    "sshproto",
    "smol",
    "door-tokio",
    "sshwire_derive",
]

[profile.release]
opt-level = 's'
lto = "fat"
debug = 1
