[package]
name = "sunset-demo-embassy-common"
description = "Shared code for Sunset demos"
version = "0.1.0"
edition = "2021"

[workspace]
# blank

[dependencies]
sunset-embassy = { path = "../../" }
sunset = { path = "../../.." }
sunset-sshwire-derive = { version = "0.1", path = "../../../sshwire-derive" }

embassy-sync = { version = "0.2.0" }
embassy-net = { version = "0.1.0", features = ["tcp", "dhcpv4", "medium-ethernet", "nightly"] }
embassy-net-driver = { version = "0.1.0" }
embassy-futures = { version = "0.1.0" }

heapless = "0.7.15"
# using local fork
# menu = "0.3"
embedded-io = { version = "0.4", features = ["async"] }

defmt = { version = "0.3", optional = true }
log = "0.4"

[features]
defmt = ["dep:defmt", "embassy-net/defmt", "embedded-io/defmt"]
log = ["embassy-net/log"]
