[package]
name = "sunset-async"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/mkj/sunset"
license = "MPL-2.0"
description = "Async wrapper for Sunset SSH"

[dependencies]
sunset = { path = "..", features = ["std", "openssh-key"] }
sunset-embassy = { path = "../embassy" }
log = { version = "0.4", features = ["release_max_level_info"] }
rpassword = "6.0"
argh = "0.1"

embassy-sync = { version = "0.1.0" }

# async feature requires nightly for async fn in trait
# https://github.com/rust-lang/rust/issues/91611
embedded-io = { version = "0.4", features = ["async", "tokio"] }

# smol = { version = "1.2" }
# futures-io = "0.3"
# futures-micro = "0.5"
# async-dup = "1.2"

# pin-utils = "0.1"
# pin-project = "1.0"
# parking_lot = { version = "0.12", features = ["arc_lock", "send_guard"] }

# "net" for AsyncFd on unix
tokio = { version = "1.19", features = ["sync", "net"] }
futures = "0.3"
moro = "0.4"

libc = "0.2"
nix = "0.24"

heapless = "0.7.10"

# TODO
pretty-hex = "0.3"
snafu = { version = "0.7", default-features = true }

[dev-dependencies]
anyhow = { version = "1.0" }
tokio = { version = "1.17", features = ["full"] }
pretty-hex = "0.3"
simplelog = "0.12"
zeroize = "1.5"
