[package]
name = "door-async"
version = "0.1.0"
edition = "2021"

[dependencies]
door-sshproto = { path = "../sshproto", features = ["std"] }
# door-sshproto = { path = "../sshproto", features = []}
log = { version = "0.4", features = ["release_max_level_info"] }
rpassword = "6.0"
argh = "0.1"

# smol = { version = "1.2" }
# futures-io = "0.3"
# futures-micro = "0.5"
# async-dup = "1.2"

# pin-utils = "0.1"
# pin-project = "1.0"
# parking_lot = { version = "0.12", features = ["arc_lock", "send_guard"] }

tokio = { version = "1.17", features = ["sync"] }
# require alpha for https://github.com/rust-lang/futures-rs/pull/2571
futures = { version = "0.4.0-alpha.0", git = "https://github.com/rust-lang/futures-rs", revision = "8b0f812f53ada0d0aeb74abc32be22ab9dafae05" }
async-trait = "0.1"

# TODO
anyhow = { version = "1.0" }
pretty-hex = "0.3"

[dev-dependencies]
snafu = { default-features = true }
tokio = { features = ["full"] }
pretty-hex = "0.3"
simplelog = "0.12"
