[package]
name = "sunset-async"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/mkj/sunset"
license = "0BSD"
description = "Async wrapper for Sunset SSH"

[dependencies]
sunset = { path = "..", features = ["std", "rsa", "openssh-key"] }
sunset-sshwire-derive = { version = "0.1", path = "../sshwire-derive" }
sunset-embassy = { path = "../embassy" }
log = { version = "0.4", features = ["release_max_level_trace"] }
rpassword = "7.2"
argh = "0.1"

ssh-key = { version = "0.5", default-features = false, features = [ "std"] }

embassy-sync = { version = "0.2.0" }
embassy-futures = { version = "0.1.0" }

# async feature requires nightly for async fn in trait
# https://github.com/rust-lang/rust/issues/91611
embedded-io = { version = "0.4", features = ["async"] }

# "net" for AsyncFd on unix
tokio = { version = "1.25", features = ["net", "io-util", "signal"] }
futures = "0.3"

libc = "0.2"
nix = "0.26"

heapless = "0.7.10"

# TODO
pretty-hex = "0.3"
# snafu = { version = "0.7", default-features = true }

[features]
# rsa is implied by sunset/std
# rsa = ["sunset/rsa"]

[dev-dependencies]
anyhow = { version = "1.0" }
pretty-hex = "0.3"
whoami = "1.3"
zeroize = "1.5"

tokio = { version = "1.17", features = ["full"] }

# adapters for tokio and async-std
embedded-io = { version = "0.4", features = ["tokio"] }

simplelog = "0.12"
# for simplelog
time = { version = "0.3", features = ["local-offset"] }
