[package]
name = "sunset-sshwire-derive"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/mkj/sunset"
license = "MPL-2.0"
description = "Derive macros for Sunset SSH packet encoder/decoder"

[lib]
proc-macro = true

[dependencies]
virtue = "0.0.13"
