[package]
name = "sunset-embassy"
version = "0.2.0-alpha"
edition = "2021"

[dependencies]
embassy-sync = { version = "0.1.0" }
embassy-net = { version = "0.1.0" }
embassy-futures = { version = "0.1.0" }
pin-utils = { version = "0.1" }

sunset = { path = "../" }

log = { version = "0.4" }
